version: 2.1
orbs:
  python: circleci/python@1.3.2
  
jobs:
  run:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - run:
          name: step 1
          command: |
            pip install --user awscli
            echo "donedone"
            aws --version
            aws s3 ls
            
workflows:
  build_and_test:
    jobs:
      - run
