version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  runStorybook:
    jobs:
      - npm install --save-dev @applitools/eyes-storybook
      - chmod +x ./runStoryBook.sh
      - ./runStoryBook.sh
