version: 2.1
orbs:
  python: circleci/python@1.3.2
  
jobs:
  run:
    steps:
      - run:
          name: step 1
          command: |
            pip install --user awscli
            aws --version
            aws s3 ls
            
workflows:
  build_and_test:
    jobs:
      - run
